### ISSUE TITLE
cool bypass

### ISSUE THREAD

**Issue by keno-tech** [Larinax999/allticket-delay-bypass#1]
Hey, I saw your bypass trick on Allticket.com and thouught it was cool! I was wondering how you were able to come up with the timeout function and why is it able to bypass the long loading time? Thanks alot!

**Comment by Larinax999** [comment]
Basically, it’s just about using common sense. Think about it: the loading icon appears because either the client or the server is processing something. If the loading icon is waiting for a response from the server (you can inspect this using DevTools), there’s nothing we can do. However, if it’s not, then think like a allticket developer. What kind of function would you use to set a timer for the loading icon to appear and disappear?

There are three possible functions: `setTimeout`, `setInterval`, or `Promise`. First, try hooking into these functions with an example like this:


```js
window.setTimeout = (...args) => {
    console.log("setTimeout called with arguments", ...args);
    return null;
};
```

If the loading icon goes away or appears faster, then you've found it! It took me about 5-10 minutes to figure this out.

Lastly, there are many other, better methods to find and bypass this.
